[versions]
activityCompose = "1.12.2"
haze = "1.7.1"
kotlin = "2.3.0"
ksp = "2.3.4"
compose = "1.10.0"
androidGradlePlugin = "9.0.0"
androidBuildTools = "31.7.2"
windowStyler = "0.3.3-SNAPSHOT"
highlights = "1.1.0"
kotlinx-datetime = "0.7.1"
jna = "5.16.0"
buildKonfig = "0.17.1"
mavenPublish = "0.35.0"
navigationEvent = "1.0.0"
navigation3="1.0.0-alpha06"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
androidx-navigationevent-compose = { module = "org.jetbrains.androidx.navigationevent:navigationevent-compose", version.ref = "navigationEvent" }

compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-ui-util = { module = "org.jetbrains.compose.ui:ui-util", version.ref = "compose" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }

haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ktor-client-java = "io.ktor:ktor-client-java:3.0.0"
jsoup = "org.jsoup:jsoup:1.16.2"
google-guava = "com.google.guava:guava:33.2.1-jre"
squareup-kotlinpoet = "com.squareup:kotlinpoet:2.1.0"
android-tools-common = { module = "com.android.tools:common", version.ref = "androidBuildTools" }
android-tools-sdk-common = { module = "com.android.tools:sdk-common", version.ref = "androidBuildTools" }
window-styler = { module = "com.mayakapps.compose:window-styler", version.ref = "windowStyler" }
highlights = { module = "dev.snipme:highlights", version.ref = "highlights" }
jna-platform = { module = "net.java.dev.jna:jna-platform-jpms", version.ref = "jna" }
jna = { module = "net.java.dev.jna:jna-jpms", version.ref = "jna" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }

android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }

build-konfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }